dist: bionic
notifications:
  email: on_failure
language: python
python: 3.8

env:
  - CONDA_ENV=py37
  - CONDA_ENV=py38

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -q -f .ci/requirements-$CONDA_ENV.yml
  - source activate test_env
install: pip install .[test,dev,doc]
script: pytest -v --doctest-modules --pyargs dalia

jobs:
  fast_finish: true
  include:
    - stage: test
      name: 'Python package'
      before_install: skip
      install:
        - pip install twine
        - python setup.py bdist_wheel sdist
      script: twine check dist/*
    - name: 'Conda package'
      before_script: conda install anaconda-client conda-build
      install: skip
      script: conda-build --no-anaconda-upload .ci/recipe/
    - name: 'Code format'
      before_install: skip
      install: pip install .[dev]
      script:
        - flake8
        - black -v --check dalia/*
    - name: 'Documentation'
      before_install: skip
      install: pip install .[doc]
      script: sphinx-build -W -b html -d docs/_build/doctrees docs/. docs/_build/html

    - stage: deploy
      if: (branch = master) AND (tag IS present)
      name: 'PyPI deploy'
      before_install: skip
      install: skip
      script: skip
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: __token__
        password:
          secure: boKPPgLHYEgBMul1+9dIm9F2PEp1knsSHhBPTAJbd7fNZ1l+CMEIZTGg0FUi1ceLyfWZ0gtWGJHMH8cB2AktLH5jB2pebXI0mOXIv2igitQ4M+UIG4AZEeMMvi3B5kPdHDDj04q0tpk+JdsVCWhir2SyUVpBEI5id4LvqJJpnvcP3wNWZzsWEpid38Hq7NR43i50LzNu+S2pS3S0VxUcoQNL5wIi5UjYe8HlLyPe3JtpCkmAj2pGlg0IGX41r4giK2l920QtoraTY2Q+7h/IuKjm+XQSsIZOyGMG75Q/NvIeQssmAjmEDH8Tj/SW1j8XqLYZ4ixNMrN6kAeWPgBkpe+2muF+AjHfw8zdIP1hZuCaCI2jfS0Mc0z3ibC/iaXYFA7wzKPiJ5CJ6ekoD0HHAo3J6iKhQzWz40gMa6YzZIvMyojvP6Y44MVy0SLD+1Fx/cEJ+pm/lhqtpwqaEz7vDqSNyfXQ8As+4eyGTOo/7MjUm/OJAHR72+2T8MbMxsfDytW67VFeDsWqaMa0PkuiWAb6B0BWcPKn1XLMNmFwGYl1ZyFoMpJki01Wa+EU1h4C+Uz/aye0erYAw4VPQI29V34JPtObOmGzkLP7uZD0n/Rajv3lqkd0k4EuUpH/w78ga24zVb2LUjV7iIc9fC0IeTNDQqc4gRP9ZNT/SG9gvuQ=
        skip_existing: true
    - name: 'Conda deploy'
      if: (branch = master) AND (tag IS NOT present)
      before_script:
        - conda install anaconda-client conda-build
        - conda config --set anaconda_upload yes
      script: conda-build --user $ANACONDA_USER --token $ANACONDA_TOKEN .ci/recipe/ --label dev
    - name: 'Conda deploy'
      if: (branch = master) AND (tag IS present)
      before_script:
        - conda install anaconda-client conda-build
        - conda config --set anaconda_upload yes
      script: conda-build --user $ANACONDA_USER --token $ANACONDA_TOKEN .ci/recipe/
