{% set version = "0.1.2a2" %}

package:
  name: dalia
  version: {{ version }}

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

source:
  - path: ../..

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.14
    - pyyaml

test:
  imports:
    - dalia
  requires:
    - pytest

about:
  home: "https://github.com/brews/dalia"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: "GPL3"
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brews

